name: ASP.NET Core WebApp Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      app-name:
        required: true
        type: string
      deployment-slot:
        required: true
        type: string
    secrets:
      azure-profile:
        required: false

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.package-name }}

      - name: Shared Repo Confirmation
        run: echo "This workflow is indeed running from shared repo"

      - name: Secret Information
        run: echo "Value of secret matches - ${{ secrets.azure-profile  == 'AZ_PRROFILE' }}"

      - name: Print name of App Service to deploy to
        run: echo "App will be deployed to ${{ inputs.app-name }}"

      - name: List files in root directory
        run: |
          Get-ChildItem -Path . | ForEach-Object { Write-Output $_.Name }
        shell: pwsh
